### PR TITLE
Signup page

### LINKED ISSUE #17: [FEATURE] Sign up Page
### Detailed description

There is no sign-up page here.

### Context

- If there is a sign-up page users can simply sign-up.
- You can create a similar design of sign-up.

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SinghalChinmay**
### Fixes Issue Number
closes #17

### Changes proposed
Create a sign-up page and fix the links related to them

### Screenshots
[Screenshot](https://chinmay-human.needs.rest/firefox_DyUkKaGl2W.png)

### Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

### Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/NewsFlash/blob/main/CODE_OF_CONDUCT.md) 🖖

---

If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
Feel free to check out other cool **open-source** repositories and communities:
[Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)

### CODE REVIEW

**Comment by kabir0x23** [comment]
Hey, i have a question, so you are doing this for hacktoberfest, right?

**Comment by SinghalChinmay** [comment]
@kabir0x23 If the PR is fine, please add the `hacktoberfest-accepted` label instead!

**Comment by kabir0x23** [comment]
> @kabir0x23 If the PR is fine, please add the `hacktoberfest-accepted` label instead!

we will add that. we know that, that we have to add hacktoberfest-accepter lable there.

**Review by 0xk4b1r — APPROVED** [review]
Nice

Thanks for contributing to this project

**Pull request merged**
